version: "3"
services:
  api:
    image: omollo/ekas-portal-api-prod
    deploy:
      replicas: 5
    ports:
      - "8082:8082"
      - "8081:8081"
    networks:
      - host
    volumes:
      - logs:/go/logs
volumes:
  logs:
networks:
  host: