version: "3"
services:
  api:
    image: ekas-portal-api-dev
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8081:8081"
    networks:
      - host
networks:
  host: