version: "3"
services:
  api:
    image: omollo/ekas-portal-api-prod
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8081:8082"
    networks:
      - host
networks:
  host: