version: "3"
services:
  api:
    image: omollo/ekas-portal-api-prod
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
    ports:
      - "8081:8081"
    networks:
      - host
networks:
  host: