# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
# dsn: "postgres://postgres:postgres@127.0.0.1:5432/go_restful?sslmode=disable"
local_dsn: "root:@tcp(127.0.0.1:3307)/ekas_portal?parseTime=true"
# local_dsn: "remote:2030-Ekas1@tcp(138.197.205.177:3306)/ekas_portal?parseTime=true"
server_dns: "root:Ekas-254@tcp(127.0.0.1:3306)/ekas_portal?parseTime=true"
# server_dns: "remote:2030-Ekas1@tcp(138.197.205.177:3306)/ekas_portal?parseTime=true"
tracking_server_url: "http://equscabanus.com/api/"
server_port: "8081"
mongo_db_dns: "mongodb://root:safcom2012@127.0.0.1:27017/?authSource=admin"
mongo_db_name: "ekas_portal"
# These are secret keys used for JWT signing and verification.
# Make sure you override these keys in production by the following environment variables:
#   RESTFUL_JWT_VERIFICATION_KEY
#   RESTFUL_JWT_SIGNING_KEY
jwt_verification_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"
jwt_signing_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"
# Uncomment the following line and set an appropriate JWT signing method, if needed
# The default signing method is HS256.
#jwt_signing_method: "HS256"

# twilio
twilio_account_sid: "ACeab16ebd80a48c1f4318f09c6ad6e33e"
twilio_auth_token : "8812492c587bf5cda4ee01a0bfedff3d"

# Africas Talking 
at_api_username: "Ekas1"
at_api_key : "13b44c5b52cbd78c4fd19d7a2aa1329ccee7f01bec94cac107dd2c8c937d1905"
